
---
apiVersion: v1
kind: Config
current-context: sri
clusters:
- name: sri
  cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ1akNDQWs2Z0F3SUJBZ0lRVVBIVWQ0NjVDRGNsVjJlS1RycXBVekFOQmdrcWhraUc5dzBCQVFzRkFEQU4KTVFzd0NRWURWUVFERXdKallUQWVGdzB5TmpBeE1ERXhNalUxTkRKYUZ3MHpOakF4TURFeE1qVTJOREphTUEweApDekFKQmdOVkJBTVRBbU5oTUlJQm9qQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FZOEFNSUlCaWdLQ0FZRUF4MkVYCmNES3VXRENUSW5DVVY3Y2p1aFRnQjcrUU9HeGdrUnFGYWxjcHFvMVlCczZES251NTNFQ0RjbFliUGF2ZlZJcW4KUVJaa28xNE52Q1A2RUdLUTQrcXkvZDczMkx2QmhwYko3SVRsRWdyQVZ5UzFnOVFoZWJmUFhWU2VBWE5uMGFRRAprY3FTZGdNeVF5T2F3YzkwU1BhT3BGcGRtYmg3cXRFT3ZNcElsZ0FpRjd1MDYyOFdJRDhETjBvd2VwNld0aHAvCjE3bUozQUY1U256NVordWlyTzNqSHFBQWpOZTU4emZEeDZUN244bUdDbVJMSXpVMEdFUWpFYWNOY2tYVHNPaVkKNDR4OForeGFlSkZZYWRmclNNT3RNWUtYcENSVUQvZnovZC9OelBMS25jYjU2S0hTMzd2S2RvQXYyT2RjcTk3QQpSSm9sTXdLWHhHSHBMcHBoUGREYTNFaFl6enhBZCt4SDZRSDFyMzBSYStwTC9UZ21yUWNpZWQzVUdYbmJMd21NCmlYSkZJbCtSNjBZRENPZEtmbjRrV2JzcllGc2VvbmRIVUhLdWc1MmpPTHQ2aHBEUWZsYlNZS2pnN1AzQzZ5MUwKWVVsd1ZXVWJZS1pETmJDSC8yQStEcDhNQTJKeDFZbEU2dENRT05KY1Z6a3hzS0g3SXBmWXliU1NFbjVaQWdNQgpBQUdqUWpCQU1BNEdBMVVkRHdFQi93UUVBd0lCcGpBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXCkJCUmwvckl3RVZYV1VLczU3ZFlUZ0xFQ3RnSW9LekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBWUVBTUJDOUo1aDcKMk1YSnV3RW9oODFtaWdjZSs1Z2ppUk5Sc0JhR1hMN2NTblh1OW1QTEE3bXJTazEwOTdiTjZOSXQwdDdpeDhaWgpSSGRROWJqVlBsd0tMT0hacWduUnRNemN6SERnTEMrMU1KbnlNS3krNTgzK095MHNJRmJvY1dvWitKNG1PNzZ3ClFvVzRTdmlMWVRYcUF6TmwxdVMxOGtPZ2ZxMXhMWnR5WTlOZkpmRy8xVGNwYnJndFZZVzJtTUs4dldsUnpRbWsKeVhneVpGVDloaTN2UG84MUVNMUNSa1pEV2w2bVlxaTI2WjFPY1U2dzhIczVVR2FLK3N5YTQwZ2JqSWVLdkUyagpFb2pva3JvakpMME4xRXh4RG1GQ0hucVVvcWhRTGN3Q2lVdjVZTjR1blZSYXA5QmRQWnRTdXBGWWhReDZkUlVJCkNwWmxHeHF5N2JXT1JvZ2xqeHMvT1dYS1RwL3p4SUtmbjcraFJVSFZzU3huUmdCMk9vSkxNL3Z5ck04WVFXWEUKS1pwRU93UEF1N004ZnQ2aEVtakd4cEhSWUMyT3NNSi9WZW5VNGVSUzBRYm5TN1VjRHZWSUgvemMzL1dmL3A4bAoyZDlweEVYWnBTRE50VDVlQUdSc01keURvU2JuTEdlUm9KNWd1WXdqV1g1MjdRVUM5dDA5bHJYSQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://api.c-47380fd.kyma.ondemand.com
contexts:
- name: sri
  context:
    cluster: sri
    user: sri
users:
- name: sri
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - "--oidc-issuer-url=https://kyma.accounts.ondemand.com"
      - "--oidc-client-id=12b13a26-d993-4d0c-aa08-5f5852bbdff6"
      - "--oidc-extra-scope=email"
      - "--oidc-extra-scope=openid"
      command: kubectl-oidc_login
      installHint: |
        kubelogin plugin is required to proceed with authentication
        # Homebrew (macOS and Linux)
        brew install int128/kubelogin/kubelogin

        # Krew (macOS, Linux, Windows and ARM)
        kubectl krew install oidc-login

        # Chocolatey (Windows)
        choco install kubelogin
