apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "beautiful-garden.fullname" . }}-config
  labels:
    {{- include "beautiful-garden.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.config.nodeEnv | quote }}
  PORT: {{ .Values.config.port | quote }}
  APP_NAME: {{ .Values.config.appName | quote }}
