apiVersion: v1
kind: Secret
metadata:
  name: {{ include "beautiful-garden.fullname" . }}-secret
  labels:
    {{- include "beautiful-garden.labels" . | nindent 4 }}
type: Opaque
data:
  MONGODB_URI: {{ include "beautiful-garden.mongodbUri" . | b64enc | quote }}
  MONGODB_ROOT_PASSWORD: {{ .Values.secrets.mongodbRootPassword | b64enc | quote }}
  MONGODB_PASSWORD: {{ .Values.secrets.mongodbPassword | b64enc | quote }}
